### PR TITLE
fix bash completion for sub-classed MulitCommands

### PR DESCRIPTION
**Pull request by makkus**
Hi there.

A quick fix for bash completion in case where one sub-classes the 'MultiCommand'. It's trivial, but let me know if you need unit tests or such...

### CODE REVIEW

**Comment by smurfix** [comment]
Closing due to nonresponsiveness.

**Comment by makkus** [comment]
Hiya, sorry, it's been ages since I submitted this. Was there anything I was supposed to do?

**Comment by smurfix** [comment]
Uh, yes. As I commented:

>  I don't understand this patch. In which case would isinstance(x,y) be any different from issubclass(type(x),y)?

so yes I need some sort of explanation why this patch is even necessary, and/or a test that shows the problem.

**Comment by makkus** [comment]
> Uh, yes. As I commented:
> 
>     I don't understand this patch. In which case would isinstance(x,y) be any different from issubclass(type(x),y)?
 
Ah, right.. I didn't see that comment anywhere (and can't find it now). Sorry, would have of course responded otherwise...

And to be honest, I can't remember exactly why I had to add that second check, doesn't make much sense to me now either when I look at it. I do remember that it did fix the problem I was having back then though, just can't remember the exact circumstances, maybe some wonky metaclass I wrote or something like that, wouldn't have been the first time :-)

Anyway, best ignore the whole thing, if I ever come across the problem again I'll give it another go and try to better explain the issue... Sorry for the noise!

**Comment by smurfix** [comment]
Not a problem. Happens to the best of us.

**Pull request closed without merging**
